# Generated by Django 5.0.3 on 2024-03-11 14:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("theatre", "0003_play_actors_play_genres_ticket_reservation"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="ticket",
            options={"ordering": ("row", "seat")},
        ),
        migrations.AlterField(
            model_name="performance",
            name="theatre_hall",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="performances",
                to="theatre.theatrehall",
            ),
        ),
        migrations.AlterField(
            model_name="play",
            name="actors",
            field=models.ManyToManyField(related_name="plays", to="theatre.actor"),
        ),
        migrations.AlterField(
            model_name="play",
            name="genres",
            field=models.ManyToManyField(related_name="plays", to="theatre.genre"),
        ),
        migrations.AlterField(
            model_name="play",
            name="title",
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reservations",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="ticket",
            name="performance",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tickets",
                to="theatre.performance",
            ),
        ),
        migrations.AlterField(
            model_name="ticket",
            name="reservation",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tickets",
                to="theatre.reservation",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="ticket",
            unique_together={("seat", "performance")},
        ),
    ]
