# Generated by Django 5.0.3 on 2024-03-13 18:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("theatre", "0005_play_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="performance",
            name="play",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="performances",
                to="theatre.play",
            ),
        ),
    ]
